name: Create pull request to github pages
run-name: ${{ github.actor }} - ${{ github.ref_name }}
on:
   pull_request:
      paths:
      - '*.md'
   push:
      paths:
      - '*.md'
   workflow_dispatch:
jobs:
    markdown-spelling:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout
         - uses: actions/checkout@v4
           with:
            ref: ${{ github.head_Ref }}
         - name: Spell Check
           uses: UnicornGlobal/spellcheck-github-actions@master
    markdown-link-check:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout
         - uses: actions/checkout@v4
           with:
               ref: ${{ github.head_Ref }}
         - name: Check links
         - uses: gaurav-nelson/github-action-markdown-link-check@v1
           with:
            use-verbose-mode: 'yes'
            folder-path: '/'
            file-extension: '.md'
